`ifndef ALU_SVH_
`define ALU_SVH_

`define ALU_OPERATION_ADD 0
`define ALU_OPERATION_SUB 1
`define ALU_OPERATION_MUL 2
`define ALU_OPERATION_OR 3
`define ALU_OPERATION_NOT 4
`define ALU_OPERATION_XOR 5
`define ALU_OPERATION_AND 6
`define ALU_OPERATION_LOGICAL_LEFT_SHIFT 7
`define ALU_OPERATION_LOGICAL_RIGHT_SHIFT 8
`define ALU_OPERATION_ARITHMETIC_LEFT_SHIFT 9
`define ALU_OPERATION_ARITHMETIC_RIGHT_SHIFT 10

`endif
